
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

// schema maps to a MongoDB collection and defines the shape of the documents within that collection
var articlesSchema = new Schema({
  id: Number,
  title: String,
  // Length Features
  characterCount: Number,
  wordCount: Number,
  syllableCount: Number,
  sentenceCount: Number,
  // Structure Features
  sectionCount: Number,
  subsectionCount: Number,
  paragraphCount: Number,
  meanSectionSize: Number,
  meanParagraphSize: Number,
  largestSectionSize: Number,
  shortestSectionSize: Number,
  largestShortestSectionRatio: Number,
  sectionSizeStandardDeviation: Number,
  meanOfSubsectionsPerSection: Number,
  abstractSize: Number,
  abstractSizeArtcileLengthRatio: Number,
  citationCount: Number,
  citationCountPerSentence: Number,
  citationCountPerSection: Number,
  externalLinksCount: Number,
  externalLinksPerSentence: Number,
  externalLinksPerSection: Number,
  imageCount: Number,
  imagePerSentence: Number,
  imagePerSection: Number,
  // Style Features
  meanSentenceSize: 0,
  largestSentenceSize: 0,
  shortestSentenceSize: 0,
  largeSentenceRate: 0,
  shortSentenceRate: 0,
  questionCount: 0,
  questionRatio: 0,
  exclamationCount: 0,
  exclamationRatio: 0,
  toBeVerbCount: 0,
  toBeVerbRatio: 0,
  toBeVerbPerSentence: 0,
  toBeVerbRate: 0,
  modalAuxiliaryVerbCount: 0,
  modalAuxiliaryVerbsRatio: 0,
  modalAuxiliaryVerbsPerSentence :0,
  modalAuxiliaryVerbsRate: 0,
  passiveVoiceCount: 0,
  passiveVoiceRatio: 0,
  passiveVoicePerSentence: 0,
  passiveVoiceRate: 0,
  numberOfSentencesThatStartWithACoordinatingConjunction: 0,
  numberOfSentencesThatStartWithADeterminer: 0,
  numberOfSentencesThatStartWithASubordinatingPrepositionOrConjunction: 0,
  numberOfSentencesThatStartWithAnAdjective: 0,
  numberOfSentencesThatStartWithANoun: 0,
  numberOfSentencesThatStartWithAPronoun: 0,
  numberOfSentencesThatStartWithAnAdverb: 0,
  numberOfSentencesThatStartWithAnArticle: 0,
  numberOfSentencesThatStartWithACoordinatingConjunctionRatio: 0,
  numberOfSentencesThatStartWithADeterminerRatio: 0,
  numberOfSentencesThatStartWithASubordinatingPrepositionOrConjunctionRatio: 0,
  numberOfSentencesThatStartWithAnAdjectiveRatio: 0,
  numberOfSentencesThatStartWithANounRatio: 0,
  numberOfSentencesThatStartWithAPronounRatio: 0,
  numberOfSentencesThatStartWithAnAdverbRatio: 0,
  numberOfSentencesThatStartWithAnArticleRatio: 0,
  // Readability Features
  automatedReadabilityIndex: Number,
  colemanLiauIndex: Number,
  fleshReadingEase: Number,
  fleschKincaidGradeLevel: Number,
  gunningFogIndex: Number,
  lasbarhetsIndex: Number,
  smogGrading: Number,
  daleChallReadabilityFormula: Number,
  // Lexical Features
  differentWordCount: Number,
  differentWordsPerSentence: Number,
  differentWordsRate: Number,
  nounCount: Number,
  nounsPerSentence: Number,
  nounsRate: Number,
  differentNounCount: Number,
  differentNounsPerSentence: Number,
  differentNounsRate: Number,
  differentNounsDifferentWordsRatio: Number,
  verbCount: Number,
  verbsPerSentence: Number,
  verbsRate: Number,
  differentVerbCount: Number,
  differentVerbsPerSentence: Number,
  differentVerbsRate: Number,
  differentVerbsDifferentWordsRatio: Number,
  pronounCount: Number,
  pronounsPerSentence: Number,
  pronounsRate: Number,
  differentPronounCount: Number,
  differentPronounsPerSentence: Number,
  differentPronounsRate: Number,
  differentPronounsDifferentWordsRatio: Number,
  adjectiveCount: Number,
  adjectivesPerSentence: Number,
  adjectivesRate: Number,
  differentAdjectiveCount: Number,
  differentAdjectivesPerSentence: Number,
  differentAdjectivesRate: Number,
  differentAdjectivesDifferentWordsRatio: Number,
  adverbCount: Number,
  adverbsPerSentence: Number,
  adverbsRate: Number,
  differentAdverbCount: Number,
  differentAdverbsPerSentence: Number,
  differentAdverbsRate: Number,
  differentAdverbsDifferentWordsRatio: Number,
  coordinatingConjunctionCount: Number,
  coordinatingConjunctionsPerSentence: Number,
  coordinatingConjunctionsRate: Number,
  differentCoordinatingConjunctionCount: Number,
  differentCoordinatingConjunctionsPerSentence: Number,
  differentCoordinatingConjunctionsRate: Number,
  differentCoordinatingConjunctionsDifferentWordsRatio: Number,
  subordinatingPrepositionAndConjunctionCount: Number,
  subordinatingPrepositionsAndConjunctionsPerSentence: Number,
  subordinatingPrepositionsAndConjunctionsRate: Number,
  differentSubordinatingPrepositionAndConjunctionCount: Number,
  differentSubordinatingPrepositionsAndConjunctionsPerSentence: Number,
  differentSubordinatingPrepositionsAndConjunctionsRate: Number,
  differentSubordinatingPrepositionsAndConjunctionsDifferentWordsRatio:Number,
  syllablesPerWord: Number,
  charactersPerWord: Number,
  // Quality Class
  qualityClass: Number
});

// instances of Models are documents
exports.Article = mongoose.model('articles', articlesSchema);






// {
//   // Length Features
//   characterCount: Number,
//   wordCount: Number,
//   syllableCount: Number,
//   sentenceCount: Number,
//   // Structure Features
//   sectionCount: Number,
//   subsectionCount: Number,
//   paragraphCount: Number,
//   meanSectionSize: Number,
//   meanParagraphSize: Number,
//   largestSectionSize: Number,
//   shortestSectionSize: Number,
//   largestShortestSectionRatio: Number,
//   sectionSizeStandardDeviation: Number,
//   meanOfSubsectionsPerSection: Number,
//   abstractSize: Number,
//   abstractSizeArtcileLengthRatio: Number,
//   citationCount: Number,
//   citationCountPerSentence: Number,
//   citationCountPerSection: Number,
//   externalLinksCount: Number,
//   externalLinksPerSentence: Number,
//   externalLinksPerSection: Number,
//   imageCount: Number,
//   imagePerSentence: Number,
//   imagePerSection: Number,
//   // Style Features
//   meanSentenceSize: Number,
//   largestSentenceSize: Number,
//   shortestSentenceSize: Number,
//   largeSentenceRate: Number,
//   shortSentenceRate: Number,
//   questionCount: Number,
//   questionRatio: Number,
//   exclamationCount: Number,
//   exclamationRatio: Number,
//   toBeVerbCount: Number,
//   toBeVerbRatio: Number,
//   toBeVerbPerSentence: Number,
//   toBeVerbRate: Number,
//   // Readability Features
//   automatedReadabilityIndex: Number,
//   colemanLiauIndex: Number,
//   fleshReadingEase: Number,
//   fleschKincaidGradeLevel: Number,
//   gunningFogIndex: Number,
//   lasbarhetsIndex: Number,
//   smogGrading: Number,
//   linsearWriteFormula: Number,
//   daleChallReadabilityFormula: Number,
//   // Lexical Features
//   differentWordCount: Number,
//   differentWordsPerSentence: Number,
//   differentWordsRate: Number,
//   nounCount: Number,
//   nounsPerSentence: Number,
//   nounsRate: Number,
//   differentNounCount: Number,
//   differentNounsPerSentence: Number,
//   differentNounsRate: Number,
//   verbCount: Number,
//   verbsPerSentence: Number,
//   verbsRate: Number,
//   differentVerbCount: Number,
//   differentVerbsPerSentence: Number,
//   differentVerbsRate: Number,
//   pronounCount: Number,
//   pronounsPerSentence: Number,
//   pronounsRate: Number,
//   differentPronounCount: Number,
//   differentPronounsPerSentence: Number,
//   differentPronounsRate: Number,
//   adjectiveCount: Number,
//   adjectivesPerSentence: Number,
//   adjectivesRate: Number,
//   differentAdjectiveCount: Number,
//   differentAdjectivesPerSentence: Number,
//   differentAdjectivesRate: Number,
//   adverbCount: Number,
//   adverbsPerSentence: Number,
//   adverbsRate: Number,
//   differentAdverbCount: Number,
//   differentAdverbsPerSentence: Number,
//   differentAdverbsRate: Number,
//   coordinatingConjunctionCount: Number,
//   coordinatingConjunctionsPerSentence: Number,
//   coordinatingConjunctionsRate: Number,
//   differentCoordinatingConjunctionCount: Number,
//   differentCoordinatingConjunctionsPerSentence: Number,
//   differentCoordinatingConjunctionsRate: Number,
//   subordinatingPrepositionAndConjunctionCount: Number,
//   subordinatingPrepositionsAndConjunctionsPerSentence: Number,
//   subordinatingPrepositionsAndConjunctionsRate: Number,
//   differentSubordinatingPrepositionAndConjunctionCount: Number,
//   differentSubordinatingPrepositionsAndConjunctionsPerSentence: Number,
//   differentSubordinatingPrepositionsAndConjunctionsRate: Number,
//   syllablesPerWord: Number,
//   charactersPerWord: Number,
//   // Quality Class
//   qualityClass: Number
//
// }
